@echo off

set PROJ_NAME=HS7A35

echo create new folder
set/a time_h=%time:~0,2%+100
set/a real_h=%time_h%-100
if %real_h% GTR 9 (
    set/a time_m=%time:~3,2%+100
) else (
    set/a time_m=%time:~2,2%+100
)
set folder=%PROJ_NAME%_%date:~0,4%%date:~5,2%%date:~8,2%_%time_h:~1,2%%time_m:~1,2%

md ..\"%folder%"

echo copy project file
cd ..\"%folder%"
xcopy /y /s ..\%PROJ_NAME%\DESIGN.sim   .\DESIGN.sim\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.srcs  .\DESIGN.srcs\
xcopy /y /s ..\%PROJ_NAME%\DESIGN.xpr   .\

echo copy USER_IP file
xcopy /y /s ..\USER_IP                  .\DESIGN.srcs\sources_1\USER_IP\

mkdir .\DESIGN.tcl
echo open_project DESIGN.xpr    >> .\DESIGN.tcl\add_set.tcl

echo //generated by run.bat     >> .\DESIGN.srcs\sources_1\TCL_DEFINE.vh

copy ..\%PROJ_NAME%\DESIGN.tcl\set_run.tcl                                      .\DESIGN.tcl\
copy .\DESIGN.tcl\*.tcl                                                         .\DESIGN.tcl\run_vivado.tcl

C:\Xilinx\Vivado\2020.1\bin\vivado -mode tcl -source .\DESIGN.tcl\run_vivado.tcl
